server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8121
          predicates:
            -  Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  registry:
    address: nacos://localhost:8848